#!/usr/bin/env python3
"""EP-025 M3/M4/M5 fixture bootstrap for the REAL pinned Asterisk provider.

Owns one real Asterisk 22.10.1 container (nexus-ep025-ast) for the
telephony integration/failure/live-fire suites. Renders the Asterisk
configuration (pjsip endpoints, ARI user) with RANDOM per-run
passwords (never committed), creates the container, waits for real
ARI health, and writes an environment file for the test processes.
Also generates baresip config dirs for the two controlled SIP
endpoints (endpoint-a / endpoint-b).

Classification:
  - Asterisk 22.10.1 (pinned image): REAL_EXTERNAL_DEPENDENCY
  - controlled SIP endpoints (baresip): CONTROLLED_TEST_FIXTURE
  - physical handsets/PSTN: NOT ASSERTED / DEFERRED

Usage:
  asterisk_bootstrap.py start   # create container, wait, write env
  asterisk_bootstrap.py teardown  # remove container + generated state
"""

import hashlib
import pathlib
import secrets
import subprocess
import sys
import time
import urllib.error
import urllib.request

ROOT = pathlib.Path(__file__).resolve().parents[3]
CONFIG_TMPL = ROOT / "infra/asterisk/config"
CANARY_DIR = ROOT / "infra/asterisk/fixture/canaries"
WORK = pathlib.Path("/tmp/ep025-ast")
ETC = WORK / "etc-asterisk"
ENV_FILE = pathlib.Path("/tmp/ep025-ast.env")

IMAGE = "andrius/asterisk:22.10.1_debian-trixie-amd64"
DIGEST = "sha256:7a22d773fe0f81adb715cd3e8df57c602726f8ef9d39deead6360e051483e280"
NAME = "nexus-ep025-ast"
ARI_BASE = "http://127.0.0.1:8088"

# EP-021 canary phrases for two-way media proof. The 8 kHz padded
# copies are played into the call (negotiated codec is PCMU/PCMA 8000
# Hz); the 16 kHz originals feed whisper.cpp at the far end after
# capture. Both are generated by the bootstrap from the committed
# 16 kHz canaries (self-contained fixture, never /tmp-only state).
CANARY_A = "/tmp/ep025-ast/audio-a/phrase_a_8k.wav"
CANARY_B = "/tmp/ep025-ast/audio-b/phrase_b_8k.wav"

GENERATED_STATE = [ETC, ENV_FILE, WORK / "baresip-a", WORK / "baresip-b", WORK / "baresip-c", WORK / "baresip-d"]


def run(cmd, **kw):
    return subprocess.run(cmd, capture_output=True, text=True, **kw)


def docker(*args):
    # rtk-tee may intercept; use the direct daemon binary.
    return run(["/usr/bin/docker", *args])


def render_templates(env: dict) -> None:
    ETC.mkdir(parents=True, exist_ok=True)
    for tmpl in CONFIG_TMPL.glob("*.tmpl"):
        text = tmpl.read_text()
        for key, value in env.items():
            text = text.replace("{{" + key.lower() + "}}", value)
        (ETC / tmpl.name.replace(".tmpl", "")).write_text(text)
    for static in CONFIG_TMPL.glob("*.conf"):
        (ETC / static.name).write_text(static.read_text())


def prepare_canaries(audio_a: pathlib.Path, audio_b: pathlib.Path) -> None:
    """Generate the 8 kHz padded playback canaries from the committed
    16 kHz originals (self-contained fixture).

    The negotiated codec is PCMU/PCMA 8000 Hz, so the in-call source
    must be 8 kHz; the canaries are padded with trailing silence so the
    call stays observable (~10 s) and baresip does not BYE at EOF.
    """
    import subprocess as sp

    src_a = CANARY_DIR / "phrase_a_16k.wav"
    src_b = CANARY_DIR / "phrase_b_16k.wav"
    if not src_a.is_file() or not src_b.is_file():
        raise SystemExit(
            "bootstrap: FAIL - committed canary wavs missing "
            f"({src_a}, {src_b})"
        )
    audio_a.mkdir(parents=True, exist_ok=True)
    audio_b.mkdir(parents=True, exist_ok=True)
    # Silence pad at 8 kHz, ~20 s (canary speech ~6 s -> ~26 s total).
    # The pad MUST outlive the whole M3 journey: baresip's aufile source
    # hangs up at EOF, and the journey needs the call alive through
    # bridge verification, DTMF, and the media hold so captures are
    # written before hangup closes them. ALWAYS regenerate: a stale pad
    # from an earlier bootstrap (old pad length) would silently shorten
    # the call.
    silence = WORK / "silence_8k.wav"
    silence.unlink(missing_ok=True)
    res = sp.run(
        [
            "ffmpeg", "-y", "-loglevel", "error",
            "-f", "lavfi", "-i", "anullsrc=r=8000:cl=mono",
            "-t", "20", str(silence),
        ],
        capture_output=True,
        text=True,
    )
    if res.returncode != 0:
        raise SystemExit(f"bootstrap: FAIL - silence generation: {res.stderr.strip()}")
    for src, out in ((src_a, CANARY_A), (src_b, CANARY_B)):
        res = sp.run(
            [
                "ffmpeg", "-y", "-loglevel", "error",
                "-i", str(src),
                "-ar", "8000", "-ac", "1",
                str(WORK / "canary_8k_raw.wav"),
            ],
            capture_output=True,
            text=True,
        )
        if res.returncode != 0:
            raise SystemExit(f"bootstrap: FAIL - 8k resample: {res.stderr.strip()}")
        res = sp.run(
            [
                "ffmpeg", "-y", "-loglevel", "error",
                "-i", str(WORK / "canary_8k_raw.wav"),
                "-i", str(silence),
                "-filter_complex", "[0:a][1:a]concat=n=2:v=0:a=1",
                str(out),
            ],
            capture_output=True,
            text=True,
        )
        if res.returncode != 0:
            raise SystemExit(f"bootstrap: FAIL - canary concat: {res.stderr.strip()}")
    print("bootstrap: canaries ready (8 kHz padded playback copies)")


def write_baresip_config(
    name: str,
    sip_name: str,
    sip_port: int,
    password: str,
    audio_dir: pathlib.Path,
    answermode: str = "auto",
) -> None:
    cfg = WORK / f"baresip-{name}"
    cfg.mkdir(parents=True, exist_ok=True)
    audio_dir.mkdir(parents=True, exist_ok=True)
    # baresip prefixes ./ to module names: modules must be loaded
    # from the CWD /usr/lib/baresip/modules (bootstrap/test runs
    # baresip with that working directory). The account loader is a
    # module and reads <configdir>/accounts.
    (cfg / "config").write_text(
        f"""# EP-025 controlled SIP endpoint {sip_name} (baresip)
module stdio.so
module menu.so
module ctrl_tcp.so
module account.so
module g711.so
module aufile.so
module ausine.so
module sndfile.so
ctrl_tcp_listen 127.0.0.1:{sip_port + 100}
audio_player aufile
audio_source aufile,{CANARY_A if name == "a" else CANARY_B}
snd_path {audio_dir}
audio_alert ausine
audio_volume 100
audio_duplex no
sip_listen 0.0.0.0:{sip_port}
sip_local_port {sip_port}
# Disable the jitter buffer for the controlled fixture. Asterisk
# 22.10.1 sends ARI-injected RFC4733 telephone-events in a DISJOINT
# RTP sequence space on the same SSRC as the bridge audio, and the
# mixing bridge takes over RTP with a NEW SSRC after one pre-bridge
# packet. libre's jbuf tracks seq_put across both transitions and
# then rejects all later audio as "too late" (ETIMEDOUT). The M3
# media proof is real RTP -> real PCMU decode -> whisper; the DTMF
# proof is the RFC4733 wire capture. Neither depends on the
# endpoint jitter buffer, so the fixture disables it (0-0 frames
# means no jbuf is allocated) to make the receive path deterministic.
jitter_buffer_delay 0 0
"""
    )
    (cfg / "accounts").write_text(
        f"# EP-025 controlled SIP endpoint {sip_name}\n"
        f"<sip:{sip_name}@127.0.0.1:5060>;auth_user={sip_name};auth_pass={password};answermode={answermode};regint=5\n"
    )


def ari_healthy(user: str, password: str, timeout: float = 120.0) -> bool:
    import base64

    token = base64.b64encode(f"{user}:{password}".encode()).decode()
    deadline = time.time() + timeout
    while time.time() < deadline:
        try:
            req = urllib.request.Request(
                f"{ARI_BASE}/ari/asterisk/info",
                headers={"Authorization": f"Basic {token}"},
            )
            with urllib.request.urlopen(req, timeout=3) as resp:
                if resp.status == 200:
                    return True
        except Exception:
            time.sleep(2)
    return False


def start() -> int:
    env = {
        "ARI_PASSWORD": secrets.token_hex(16),
        "ENDPOINT_A_PASSWORD": secrets.token_hex(12),
        "ENDPOINT_B_PASSWORD": secrets.token_hex(12),
        "ENDPOINT_C_PASSWORD": secrets.token_hex(12),
        "ENDPOINT_D_PASSWORD": secrets.token_hex(12),
        "ENDPOINT_X_PASSWORD": secrets.token_hex(12),
        "ENDPOINT_R_PASSWORD": secrets.token_hex(12),
        "ENDPOINT_S_PASSWORD": secrets.token_hex(12),
        "ENDPOINT_T_PASSWORD": secrets.token_hex(12),
        "ENDPOINT_U_PASSWORD": secrets.token_hex(12),
        "ENDPOINT_V_PASSWORD": secrets.token_hex(12),
    }
    render_templates(env)
    prepare_canaries(WORK / "audio-a", WORK / "audio-b")
    write_baresip_config("a", "endpoint-a", 5070, env["ENDPOINT_A_PASSWORD"], WORK / "audio-a")
    # NOTE: baresip binds TCP on sip_local_port AND sip_local_port+1
    # (observed on v1.0.0). Endpoint ports must therefore be spaced
    # apart by more than 1 to avoid cross-endpoint socket collisions.
    write_baresip_config("b", "endpoint-b", 5080, env["ENDPOINT_B_PASSWORD"], WORK / "audio-b")
    # endpoint-c: MANUAL answer (the M4 NO_ANSWER / REJECT mechanisms
    # need an endpoint that does not auto-answer; the test drives
    # answer/reject through baresip's stdio commands).
    write_baresip_config("c", "endpoint-c", 5090, env["ENDPOINT_C_PASSWORD"], WORK / "audio-c", answermode="manual")
    # endpoint-d: second auto-answer endpoint (M4 exact-target /
    # simultaneous-session tests need two independent calls).
    write_baresip_config("d", "endpoint-d", 5100, env["ENDPOINT_D_PASSWORD"], WORK / "audio-d")

    # Remove any stale container from a previous run.
    docker("rm", "-f", NAME)

    image_ref = f"{IMAGE}@{DIGEST}"
    res = docker(
        "run",
        "-d",
        "--name",
        NAME,
        "-p",
        "127.0.0.1:8088:8088",
        "-p",
        "127.0.0.1:5060:5060/udp",
        "-p",
        "127.0.0.1:5061:5061/tcp",
        "-p",
        "127.0.0.1:10000-10099:10000-10099/udp",
        "-v",
        f"{ETC}:/etc/asterisk",
        image_ref,
    )
    if res.returncode != 0:
        print(f"bootstrap: FAIL - docker run: {res.stderr.strip()}", file=sys.stderr)
        return 1

    if not ari_healthy("nexus", env["ARI_PASSWORD"]):
        print("bootstrap: FAIL - ARI did not become healthy", file=sys.stderr)
        docker("logs", "--tail", "40", NAME)
        docker("rm", "-f", NAME)
        return 1

    # ARI channel recording writes into the container's recording spool
    # directory. The base image ships without it; create it now or the
    # LF-012 record REST call fails with ENOENT -> 500.
    res = docker("exec", NAME, "mkdir", "-p", "/var/spool/asterisk/recording")
    if res.returncode != 0:
        print(f"bootstrap: FAIL - create recording spool: {res.stderr.strip()}", file=sys.stderr)
        docker("rm", "-f", NAME)
        return 1
    res = docker("exec", NAME, "chown", "asterisk:asterisk", "/var/spool/asterisk/recording")
    if res.returncode != 0:
        print(f"bootstrap: FAIL - chown recording spool: {res.stderr.strip()}", file=sys.stderr)
        docker("rm", "-f", NAME)
        return 1

    # ARI playback of a sound file requires the language sounds dir to
    # exist (docker cp needs a real target path); the base image ships
    # without the en/ tree.
    res = docker("exec", NAME, "mkdir", "-p", "/var/lib/asterisk/sounds/en")
    if res.returncode != 0:
        print(f"bootstrap: FAIL - create sounds dir: {res.stderr.strip()}", file=sys.stderr)
        docker("rm", "-f", NAME)
        return 1

    with ENV_FILE.open("w") as f:
        f.write(f"NEXUS_ARI_URL={ARI_BASE}\n")
        f.write(f"NEXUS_ARI_USER=nexus\n")
        f.write(f"NEXUS_ARI_PASSWORD={env['ARI_PASSWORD']}\n")
        f.write(f"NEXUS_EP025_AST_CONTAINER={NAME}\n")
        f.write(f"NEXUS_EP025_AST_IMAGE={image_ref}\n")
        f.write(f"NEXUS_SIP_A_PASSWORD={env['ENDPOINT_A_PASSWORD']}\n")
        f.write(f"NEXUS_SIP_B_PASSWORD={env['ENDPOINT_B_PASSWORD']}\n")
        f.write(f"NEXUS_SIP_C_PASSWORD={env['ENDPOINT_C_PASSWORD']}\n")
        f.write(f"NEXUS_SIP_D_PASSWORD={env['ENDPOINT_D_PASSWORD']}\n")
        f.write(f"NEXUS_SIP_X_PASSWORD={env['ENDPOINT_X_PASSWORD']}\n")
        f.write(f"NEXUS_SIP_R_PASSWORD={env['ENDPOINT_R_PASSWORD']}\n")
        f.write(f"NEXUS_SIP_S_PASSWORD={env['ENDPOINT_S_PASSWORD']}\n")
        f.write(f"NEXUS_SIP_T_PASSWORD={env['ENDPOINT_T_PASSWORD']}\n")
        f.write(f"NEXUS_SIP_U_PASSWORD={env['ENDPOINT_U_PASSWORD']}\n")
        f.write(f"NEXUS_SIP_V_PASSWORD={env['ENDPOINT_V_PASSWORD']}\n")
        f.write(f"NEXUS_BARESIP_A_DIR={WORK / 'baresip-a'}\n")
        f.write(f"NEXUS_BARESIP_B_DIR={WORK / 'baresip-b'}\n")
        f.write(f"NEXUS_BARESIP_C_DIR={WORK / 'baresip-c'}\n")
        f.write(f"NEXUS_BARESIP_D_DIR={WORK / 'baresip-d'}\n")
        f.write(f"NEXUS_EP025_AUDIO_A_DIR={WORK / 'audio-a'}\n")
        f.write(f"NEXUS_EP025_AUDIO_B_DIR={WORK / 'audio-b'}\n")
        f.write(f"NEXUS_EP025_AUDIO_C_DIR={WORK / 'audio-c'}\n")
        f.write(f"NEXUS_EP025_AUDIO_D_DIR={WORK / 'audio-d'}\n")
        f.write(f"NEXUS_EP025_EVENTS={WORK / 'ari-events.jsonl'}\n")
        f.write("NEXUS_WHISPER_CLI=/opt/nexus-whisper/build/bin/whisper-cli\n")
        f.write("NEXUS_WHISPER_MODEL=/opt/nexus-voice-models/ggml-tiny.en.bin\n")

    print(f"bootstrap: ok container={NAME}")
    return 0


def teardown() -> int:
    res = docker("rm", "-f", NAME)
    if res.returncode != 0 and "No such container" not in res.stderr:
        print(f"teardown: FAIL - {res.stderr.strip()}", file=sys.stderr)
        return 1
    leftovers = docker("ps", "-aq", "--filter", f"name={NAME}").stdout.strip()
    if leftovers:
        print(f"teardown: FAIL - leaked container {leftovers}", file=sys.stderr)
        return 1
    for path in GENERATED_STATE:
        if path.exists():
            if path.is_dir():
                import shutil

                shutil.rmtree(path, ignore_errors=True)
            else:
                path.unlink(missing_ok=True)
    return 0


def main() -> int:
    mode = sys.argv[1] if len(sys.argv) > 1 else "start"
    if mode == "start":
        return start()
    if mode == "teardown":
        return teardown()
    print(f"bootstrap: unknown mode {mode}", file=sys.stderr)
    return 2


if __name__ == "__main__":
    sys.exit(main())
