"""Code generated by packages/contracts/scripts/generate.py from schemas/. DO NOT EDIT."""

from __future__ import annotations
from typing import Any, Literal, NotRequired, TypedDict

class ActionRequest(TypedDict):
    action_id: str
    approval_class: str
    arguments: dict[str, object]
    capability_id: str
    expected_state: dict[str, object]
    idempotency_key: str
    invocation: InvocationContext
    principal_id: str
    reversal: str
    risk: Literal["R0", "R1", "R2", "R3", "R4"]
    tenant_id: str

class CapabilityDescriptor(TypedDict):
    approval: Literal["NONE", "POLICY", "HUMAN", "STRONG_HUMAN", "FOUR_EYES"]
    availability: Literal["AVAILABLE", "DEGRADED", "UNAVAILABLE", "UNCERTIFIED"]
    class_: Literal["QUERY", "COMMAND", "WORKFLOW", "STREAM", "ADMINISTRATIVE"]
    data_classes: NotRequired[list[str]]
    description: str
    event_types: NotRequired[list[str]]
    id: str
    idempotency: Literal["NOT_APPLICABLE", "OPTIONAL", "REQUIRED"]
    input_schema: str
    locality: NotRequired[Literal["ANY", "CONTROL_PLANE", "HOME_EDGE", "CLIENT_DEVICE", "HARDWARE_NODE"]]
    output_schema: str
    provider_id: NotRequired[str | None]
    required_scopes: list[str]
    reversal: Literal["NONE", "COMPENSATING", "SNAPSHOT", "IRREVERSIBLE"]
    risk: Literal["R0", "R1", "R2", "R3", "R4"]
    version: str

class ConnectorManifest(TypedDict):
    capabilities: list[CapabilityDescriptor]
    certification: NotRequired[Literal["UNCERTIFIED", "LAB", "CERTIFIED", "DEPRECATED"]]
    data_classes: NotRequired[list[str]]
    events: list[str]
    health: str
    id: str
    license: str
    network_origins: list[str]
    runtime: Literal["RUST", "PYTHON", "TYPESCRIPT", "WASM", "SIDECAR", "APPLIANCE"]
    secrets: list[str]
    tier: Literal["TIER1", "TIER2", "TIER3"]
    version: str

class DeploymentProfile(TypedDict):
    backup: dict[str, object]
    components: list[str]
    id: str
    mode: Literal["MANAGED", "BYOC", "EXISTING_SSH", "HYBRID", "FULLY_LOCAL"]
    nodes: list[dict[str, object]]
    release_channel: Literal["STABLE", "BETA", "DEVELOPER", "PINNED"]
    remote_access: dict[str, object]

class EventEnvelope(TypedDict):
    actor_ref: NotRequired[str | None]
    causation_id: NotRequired[str | None]
    correlation_id: str
    data_class: str
    event_id: str
    event_type: str
    observed_at: NotRequired[str | None]
    occurred_at: str
    payload: dict[str, object]
    request_id: NotRequired[str | None]
    schema_version: str
    source: str
    subject: str
    tenant_id: str

class InvocationContext(TypedDict):
    approval_id: NotRequired[str | None]
    causation_id: NotRequired[str | None]
    channel: NotRequired[str | None]
    correlation_id: str
    device_id: NotRequired[str | None]
    external_actor_id: str
    external_actor_type: Literal["HUMAN", "SERVICE", "AGENT", "DEVICE", "SYSTEM"]
    objective_id: NotRequired[str | None]
    origin_system: str
    request_id: str
    room_id: NotRequired[str | None]
    task_id: NotRequired[str | None]

class MemoryRecord(TypedDict):
    actor: str
    confidence: float
    content: dict[str, object]
    content_hash: str
    created_at: str
    derived_from: NotRequired[list[str]]
    embedding_ref: NotRequired[str | None]
    memory_id: str
    memory_type: Literal["WORKING", "EPISODIC", "SEMANTIC", "ENTITY", "PROCEDURAL", "DECISION", "SKILL", "SYSTEM"]
    namespace: str
    observed_at: str
    purpose: str
    retention: str
    sensitivity: str
    source: str
    status: Literal["PROPOSED", "ACTIVE", "SUPERSEDED", "REJECTED", "DELETED"]
    supersedes: NotRequired[str | None]
    tenant_id: str

class NexusControlObject(TypedDict):
    ambiguity: float
    approval_required: bool
    confidence: float
    entities: dict[str, object]
    escalation_reason: NotRequired[str | None]
    executable_instruction: bool
    intent: str
    privacy: Literal["PUBLIC", "HOUSEHOLD", "PERSONAL", "SENSITIVE", "BUSINESS_CONFIDENTIAL", "SECURITY", "SECRET"]
    required_capabilities: list[str]
    risk: Literal["R0", "R1", "R2", "R3", "R4"]
    route: Literal["DETERMINISTIC", "REFLEX", "CHEAP_API", "FRONTIER_API", "SPECIALIST_AGENT", "CLARIFY", "REJECT"]
    schema_version: Literal["1.0.0"]
    workflow: NotRequired[dict[str, object] | None]

class NotificationEnvelope(TypedDict):
    action_ref: NotRequired[str | None]
    channels: list[Literal["MOBILE_PUSH", "DESKTOP", "SPEAKER", "SMS", "EMAIL", "PHONE", "WATCH", "CAR"]]
    correlation_id: str
    expires_at: str
    notification_id: str
    person_id: str
    privacy: str
    summary: str
    title: str
    urgency: Literal["LOW", "NORMAL", "HIGH", "CRITICAL"]


WIRE_ALIASES: dict[str, dict[str, str]] = {
    "CapabilityDescriptor": {
        "class_": "class",
    },
}


def to_wire(class_name: str, obj: dict[str, Any]) -> dict[str, Any]:
    """Rename Python-safe identifiers to canonical wire names."""
    aliases = WIRE_ALIASES.get(class_name, {})
    return {aliases.get(k, k): v for k, v in obj.items()}


def from_wire(class_name: str, obj: dict[str, Any]) -> dict[str, Any]:
    """Rename canonical wire names back to Python-safe identifiers."""
    aliases = {v: k for k, v in WIRE_ALIASES.get(class_name, {}).items()}
    return {aliases.get(k, k): v for k, v in obj.items()}
