"""Code generated by packages/contracts/scripts/generate.py from schemas/. DO NOT EDIT."""

from __future__ import annotations
from typing import Any, NotRequired, TypedDict

class ActionRequest(TypedDict):
    action_id: str
    approval_class: str
    arguments: dict[str, object]
    capability_id: str
    expected_state: dict[str, object]
    idempotency_key: str
    invocation: object
    principal_id: str
    reversal: str
    risk: str
    tenant_id: str

class CapabilityDescriptor(TypedDict):
    approval: str
    availability: str
    class_: str
    data_classes: NotRequired[list[str]]
    description: str
    event_types: NotRequired[list[str]]
    id: str
    idempotency: str
    input_schema: str
    locality: NotRequired[str]
    output_schema: str
    provider_id: NotRequired[str | None]
    required_scopes: list[str]
    reversal: str
    risk: str
    version: str

class ConnectorManifest(TypedDict):
    capabilities: list[object]
    certification: NotRequired[str]
    data_classes: NotRequired[list[str]]
    events: list[str]
    health: str
    id: str
    license: str
    network_origins: list[str]
    runtime: str
    secrets: list[str]
    tier: str
    version: str

class DeploymentProfile(TypedDict):
    backup: dict[str, object]
    components: list[str]
    id: str
    mode: str
    nodes: list[dict[str, object]]
    release_channel: str
    remote_access: dict[str, object]

class EventEnvelope(TypedDict):
    actor_ref: NotRequired[str | None]
    causation_id: NotRequired[str | None]
    correlation_id: str
    data_class: str
    event_id: str
    event_type: str
    observed_at: NotRequired[str | None]
    occurred_at: str
    payload: dict[str, object]
    request_id: NotRequired[str | None]
    schema_version: str
    source: str
    subject: str
    tenant_id: str

class InvocationContext(TypedDict):
    approval_id: NotRequired[str | None]
    causation_id: NotRequired[str | None]
    channel: NotRequired[str | None]
    correlation_id: str
    device_id: NotRequired[str | None]
    external_actor_id: str
    external_actor_type: str
    objective_id: NotRequired[str | None]
    origin_system: str
    request_id: str
    room_id: NotRequired[str | None]
    task_id: NotRequired[str | None]

class MemoryRecord(TypedDict):
    actor: str
    confidence: float
    content: dict[str, object]
    content_hash: str
    created_at: str
    derived_from: NotRequired[list[str]]
    embedding_ref: NotRequired[str | None]
    memory_id: str
    memory_type: str
    namespace: str
    observed_at: str
    purpose: str
    retention: str
    sensitivity: str
    source: str
    status: str
    supersedes: NotRequired[str | None]
    tenant_id: str

class NexusControlObject(TypedDict):
    ambiguity: float
    approval_required: bool
    confidence: float
    entities: dict[str, object]
    escalation_reason: NotRequired[str | None]
    executable_instruction: bool
    intent: str
    privacy: str
    required_capabilities: list[str]
    risk: str
    route: str
    schema_version: object
    workflow: NotRequired[dict[str, object] | None]

class NotificationEnvelope(TypedDict):
    action_ref: NotRequired[str | None]
    channels: list[str]
    correlation_id: str
    expires_at: str
    notification_id: str
    person_id: str
    privacy: str
    summary: str
    title: str
    urgency: str
