#!/usr/bin/env python3
"""Nexus GeneratedContractPipeline (EP-001).

Reads canonical JSON Schema 2020-12 documents under schemas/ and emits
language bindings:
  - Rust:        crates/nexus-contracts/src/generated.rs
  - TypeScript:  packages/contracts/src/generated.ts
  - Python:      python/nexus_contracts/generated.py

The schemas are the single cross-language contract source. Handwritten
duplicate DTOs are forbidden (schemas/README.md). The generator is
deterministic: identical input schemas produce byte-identical output, which
the generated_contracts_match tests enforce.

Usage:
  python3 packages/contracts/scripts/generate.py [--check]
"""
from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[3]
SCHEMAS = ROOT / "schemas"
RUST_OUT = ROOT / "crates/nexus-contracts/src/generated.rs"
TS_OUT = ROOT / "packages/contracts/src/generated.ts"
PY_OUT = ROOT / "python/nexus_contracts/generated.py"

HEADER = "// Code generated by packages/contracts/scripts/generate.py from schemas/. DO NOT EDIT.\n"


def pascal(name: str) -> str:
    parts = re.split(r"[^A-Za-z0-9]+", name)
    return "".join(p.capitalize() for p in parts if p)


def snake(name: str) -> str:
    return re.sub(r"(?<!^)(?=[A-Z])", "_", name).lower()


def camel(name: str) -> str:
    head, *rest = name.split("_")
    return head + "".join(part[:1].upper() + part[1:] for part in rest)


def ts_type(prop: dict, required: bool) -> str:
    t = prop.get("type")
    if "enum" in prop:
        return " | ".join(json.dumps(v) for v in prop["enum"])
    if isinstance(t, list):
        members: list[str] = []
        for x in t:
            if x == "null":
                members.append("null")
            else:
                members.append(ts_type({**prop, "type": x}, True))
        seen: set[str] = set()
        uniq = [m for m in members if not (m in seen or seen.add(m))]
        base = " | ".join(uniq)
        if not required and "null" not in uniq:
            base = f"{base} | null"
        return base
    if t == "string":
        base = "string"
    elif t == "integer":
        base = "number"
    elif t == "number":
        base = "number"
    elif t == "boolean":
        base = "boolean"
    elif t == "array":
        items = prop.get("items", {})
        base = f"Array<{ts_type(items, True)}>"
    elif t == "object":
        base = "Record<string, unknown>"
    elif t == "null":
        base = "null"
    else:
        base = "unknown"
    return base if required else f"{base} | null"


def rust_type(prop: dict) -> str:
    t = prop.get("type")
    if "enum" in prop:
        return "String"  # enums stay strings in the generated Rust value layer
    if isinstance(t, list):
        inner = rust_type({**prop, "type": t[0]})
        return f"Option<{inner}>" if "null" in t else inner
    if t == "string":
        return "String"
    if t in ("integer", "number"):
        return "f64"
    if t == "boolean":
        return "bool"
    if t == "array":
        items = prop.get("items", {})
        return f"Vec<{rust_type(items)}>"
    if t == "object":
        return "serde_json::Value"
    return "serde_json::Value"


def py_type(prop: dict) -> str:
    t = prop.get("type")
    if "enum" in prop:
        return "str"
    if isinstance(t, list):
        inner = py_type({**prop, "type": t[0]})
        return f"{inner} | None" if "null" in t else inner
    if t == "string":
        return "str"
    if t in ("integer", "number"):
        return "float"
    if t == "boolean":
        return "bool"
    if t == "array":
        items = prop.get("items", {})
        return f"list[{py_type(items)}]"
    if t == "object":
        return "dict[str, object]"
    return "object"


def load_schemas() -> list[tuple[str, str, dict]]:
    out = []
    for path in sorted(SCHEMAS.glob("*.json")):
        doc = json.loads(path.read_text(encoding="utf-8"))
        name = path.stem.replace(".schema", "")
        out.append((name, doc.get("$id", ""), doc))
    return out


def gen_rust(schemas: list[tuple[str, str, dict]]) -> str:
    lines = [HEADER, "use serde::{Deserialize, Serialize};", ""]
    for name, _, doc in schemas:
        struct = pascal(name)
        lines.append(f"#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]")
        lines.append(f"#[serde(rename_all = \"camelCase\")]")
        lines.append(f"pub struct {struct} {{")
        for pname, prop in doc.get("properties", {}).items():
            rtype = rust_type(prop)
            optional = pname not in doc.get("required", [])
            if optional:
                lines.append(f"    #[serde(skip_serializing_if = \"Option::is_none\")]")
                lines.append(f"    pub {snake(pname)}: Option<{rtype}>,")
            else:
                lines.append(f"    pub {snake(pname)}: {rtype},")
        lines.append("}")
        lines.append("")
    return "\n".join(lines)


def gen_ts(schemas: list[tuple[str, str, dict]]) -> str:
    lines = [HEADER]
    jv_members = ["string", "number", "boolean", "null", "JsonValue[]", "{ [k: string]: JsonValue }"]
    jv_inline = "export type JsonValue = " + " | ".join(jv_members) + ";"
    if len(jv_inline) <= 80:
        lines.append(jv_inline)
    else:
        lines.append("export type JsonValue =")
        for i, m in enumerate(jv_members):
            lines.append(f"  | {m}{';' if i == len(jv_members) - 1 else ''}")
    lines.append("")
    for name, _, doc in schemas:
        iface = pascal(name)
        lines.append(f"export interface {iface} {{")
        for pname, prop in doc.get("properties", {}).items():
            required = pname in doc.get("required", [])
            t = ts_type(prop, required)
            opt = "" if required else "?"
            pname_ts = f"{camel(pname)}{opt}"
            inline = f"  {pname_ts}: {t};"
            if len(inline) <= 80 or " | " not in t:
                lines.append(inline)
                continue
            if t.startswith("Array<") and t.endswith(">"):
                inner = t[len("Array<"):-1]
                members = [m.strip() for m in inner.split(" | ")]
                lines.append(f"  {pname_ts}: Array<")
                for m in members:
                    lines.append(f"    | {m}")
                lines.append("  >;")
            else:
                members = [m.strip() for m in t.split(" | ")]
                lines.append(f"  {pname_ts}:")
                for i, m in enumerate(members):
                    suffix = ";" if i == len(members) - 1 else ""
                    lines.append(f"    | {m}{suffix}")
        lines.append("}")
        lines.append("")
    return "\n".join(lines)


PY_KEYWORDS = {
    "False", "None", "True", "and", "as", "assert", "async", "await",
    "break", "class", "continue", "def", "del", "elif", "else", "except",
    "finally", "for", "from", "global", "if", "import", "in", "is",
    "lambda", "nonlocal", "not", "or", "pass", "raise", "return", "try",
    "while", "with", "yield",
}


def py_name(name: str) -> str:
    """Python-safe field name: keywords get a trailing underscore (PEP 8)."""
    candidate = snake(name)
    return candidate + "_" if candidate in PY_KEYWORDS else candidate


def gen_py(schemas: list[tuple[str, str, dict]]) -> str:
    lines = ['"""Code generated by packages/contracts/scripts/generate.py from schemas/. DO NOT EDIT."""', ""]
    lines.append("from __future__ import annotations")
    lines.append("from typing import Any, NotRequired, TypedDict")
    lines.append("")
    for name, _, doc in schemas:
        class_name = pascal(name)
        lines.append(f"class {class_name}(TypedDict):")
        props = doc.get("properties", {})
        if not props:
            lines.append("    pass")
        for pname, prop in props.items():
            ptype = py_type(prop)
            required = pname in doc.get("required", [])
            field = py_name(pname)
            if required:
                lines.append(f"    {field}: {ptype}")
            else:
                lines.append(f"    {field}: NotRequired[{ptype}]")
        lines.append("")
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="verify committed bindings match schemas")
    args = parser.parse_args()

    schemas = load_schemas()
    rust = gen_rust(schemas)
    ts = gen_ts(schemas)
    py = gen_py(schemas)

    targets = {
        RUST_OUT: rust,
        TS_OUT: ts,
        PY_OUT: py,
    }
    failures = []
    for path, content in targets.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        if args.check:
            if not path.exists():
                failures.append(f"{path} missing")
            elif path.read_text(encoding="utf-8") != content:
                failures.append(f"{path} out of date")
        else:
            path.write_text(content, encoding="utf-8")
    if failures:
        print("contract generation: FAIL - " + "; ".join(failures), file=sys.stderr)
        return 1
    print(f"contract generation: ok ({len(schemas)} schemas)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
