#!/usr/bin/env python3
"""Nexus GeneratedContractPipeline (EP-001, EP-002 M2).

Reads canonical JSON Schema 2020-12 documents under schemas/ and emits
language bindings:
  - Rust:        crates/nexus-contracts/src/generated.rs
  - TypeScript:  packages/contracts/src/generated.ts
  - Python:      python/nexus_contracts/generated.py
  - Dart:        packages/contracts/src/generated.dart

The schemas are the single cross-language contract source. Handwritten
duplicate DTOs are forbidden (schemas/README.md). The generator is
deterministic: identical input schemas produce byte-identical output, which
the generated_contracts_match tests enforce.

Wire-name doctrine (EP-002 M2): the canonical wire name of every field is
the schema property name verbatim (snake_case). No camelCase conversion is
applied in any language; languages that need keyword-safe identifiers
(Python class_, Dart class_) map back to the canonical name through explicit
aliases in to_wire/from_wire (Python) and fromJson/toJson (Dart). A schema
`const` is emitted as a typed constant, never as an unconstrained
Value/unknown/object. `$ref` properties resolve to the referenced generated
type name.

Usage:
  python3 packages/contracts/scripts/generate.py [--check]
"""
from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[3]
SCHEMAS = ROOT / "schemas"
RUST_OUT = ROOT / "crates/nexus-contracts/src/generated.rs"
TS_OUT = ROOT / "packages/contracts/src/generated.ts"
PY_OUT = ROOT / "python/nexus_contracts/generated.py"
DART_OUT = ROOT / "packages/contracts/src/generated.dart"

HEADER = "// Code generated by packages/contracts/scripts/generate.py from schemas/. DO NOT EDIT.\n"


def pascal(name: str) -> str:
    parts = re.split(r"[^A-Za-z0-9]+", name)
    return "".join(p.capitalize() for p in parts if p)


def snake(name: str) -> str:
    return re.sub(r"(?<!^)(?=[A-Z])", "_", name).lower()


def ref_type_name(ref: str) -> str:
    """Resolve a $ref (e.g. invocation-context.schema.json) to a type name."""
    stem = Path(ref).stem
    if stem.endswith(".schema"):
        stem = stem[: -len(".schema")]
    return pascal(stem)


def const_value(prop: dict):
    return prop.get("const")


def is_const(prop: dict) -> bool:
    return "const" in prop


def rust_type(prop: dict) -> str:
    if "$ref" in prop:
        return ref_type_name(prop["$ref"])
    if is_const(prop):
        v = const_value(prop)
        if isinstance(v, bool):
            return "bool"
        if isinstance(v, (int, float)):
            return "f64"
        return "String"
    t = prop.get("type")
    if "enum" in prop:
        return "String"  # enums stay strings in the generated Rust value layer
    if isinstance(t, list):
        inner = rust_type({**prop, "type": t[0]})
        return f"Option<{inner}>" if "null" in t else inner
    if t == "string":
        return "String"
    if t in ("integer", "number"):
        return "f64"
    if t == "boolean":
        return "bool"
    if t == "array":
        items = prop.get("items", {})
        return f"Vec<{rust_type(items)}>"
    if t == "object":
        return "serde_json::Value"
    return "serde_json::Value"


def ts_type(prop: dict, required: bool) -> str:
    if "$ref" in prop:
        base = ref_type_name(prop["$ref"])
        return base if required else f"{base} | null"
    if is_const(prop):
        return json.dumps(const_value(prop))
    t = prop.get("type")
    if "enum" in prop:
        return " | ".join(json.dumps(v) for v in prop["enum"])
    if isinstance(t, list):
        members: list[str] = []
        for x in t:
            if x == "null":
                members.append("null")
            else:
                members.append(ts_type({**prop, "type": x}, True))
        seen: set[str] = set()
        uniq = [m for m in members if not (m in seen or seen.add(m))]
        base = " | ".join(uniq)
        if not required and "null" not in uniq:
            base = f"{base} | null"
        return base
    if t == "string":
        base = "string"
    elif t == "integer":
        base = "number"
    elif t == "number":
        base = "number"
    elif t == "boolean":
        base = "boolean"
    elif t == "array":
        items = prop.get("items", {})
        base = f"Array<{ts_type(items, True)}>"
    elif t == "object":
        base = "Record<string, unknown>"
    elif t == "null":
        base = "null"
    else:
        base = "unknown"
    return base if required else f"{base} | null"


def py_type(prop: dict) -> str:
    if "$ref" in prop:
        return ref_type_name(prop["$ref"])
    if is_const(prop):
        v = const_value(prop)
        return f'Literal[{json.dumps(v)}]'
    t = prop.get("type")
    if "enum" in prop:
        vals = ", ".join(json.dumps(v) for v in prop["enum"])
        return f"Literal[{vals}]"
    if isinstance(t, list):
        inner = py_type({**prop, "type": t[0]})
        return f"{inner} | None" if "null" in t else inner
    if t == "string":
        return "str"
    if t in ("integer", "number"):
        return "float"
    if t == "boolean":
        return "bool"
    if t == "array":
        items = prop.get("items", {})
        return f"list[{py_type(items)}]"
    if t == "object":
        return "dict[str, object]"
    return "object"


def dart_type(prop: dict) -> str:
    """Base Dart type WITHOUT the top-level nullability suffix.

    Nullability (schema nullable OR optional) is applied once by the
    field/parameter/fromJson emission logic so `String??` can never occur.
    """
    if "$ref" in prop:
        return ref_type_name(prop["$ref"])
    if is_const(prop):
        return "String"  # Dart has no literal types; constant emitted as static const
    t = prop.get("type")
    if "enum" in prop:
        return "String"
    if isinstance(t, list):
        inner = dart_type({**prop, "type": t[0]})
        return inner
    if t == "string":
        return "String"
    if t == "integer":
        return "int"
    if t == "number":
        return "double"
    if t == "boolean":
        return "bool"
    if t == "array":
        items = prop.get("items", {})
        return f"List<{dart_type(items)}>"
    if t == "object":
        return "Map<String, dynamic>"
    return "dynamic"


def dart_nullable(prop: dict, optional: bool) -> bool:
    """A Dart field is nullable when the schema allows null OR the field is optional."""
    if optional:
        return True
    t = prop.get("type")
    return isinstance(t, list) and "null" in t


def load_schemas() -> list[tuple[str, str, dict]]:
    out = []
    for path in sorted(SCHEMAS.glob("*.json")):
        doc = json.loads(path.read_text(encoding="utf-8"))
        name = path.stem.replace(".schema", "")
        out.append((name, doc.get("$id", ""), doc))
    return out


def gen_rust(schemas: list[tuple[str, str, dict]]) -> str:
    lines = [HEADER, "use serde::{Deserialize, Serialize};", ""]
    for name, _, doc in schemas:
        struct = pascal(name)
        lines.append("#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]")
        if doc.get("additionalProperties") is False:
            lines.append("#[serde(deny_unknown_fields)]")
        lines.append(f"pub struct {struct} {{")
        for pname, prop in doc.get("properties", {}).items():
            rtype = rust_type(prop)
            optional = pname not in doc.get("required", [])
            if optional:
                lines.append('    #[serde(skip_serializing_if = "Option::is_none")]')
                lines.append(f"    pub {pname}: Option<{rtype}>,")
            else:
                lines.append(f"    pub {pname}: {rtype},")
        lines.append("}")
        lines.append("")
    return "\n".join(lines)


def gen_ts(schemas: list[tuple[str, str, dict]]) -> str:
    lines = [HEADER]
    jv_members = ["string", "number", "boolean", "null", "JsonValue[]", "{ [k: string]: JsonValue }"]
    jv_inline = "export type JsonValue = " + " | ".join(jv_members) + ";"
    if len(jv_inline) <= 80:
        lines.append(jv_inline)
    else:
        lines.append("export type JsonValue =")
        for i, m in enumerate(jv_members):
            lines.append(f"  | {m}{';' if i == len(jv_members) - 1 else ''}")
    lines.append("")
    for name, _, doc in schemas:
        iface = pascal(name)
        lines.append(f"export interface {iface} {{")
        for pname, prop in doc.get("properties", {}).items():
            required = pname in doc.get("required", [])
            t = ts_type(prop, required)
            opt = "" if required else "?"
            inline = f"  {pname}{opt}: {t};"
            if len(inline) <= 80 or " | " not in t:
                lines.append(inline)
                continue
            if t.startswith("Array<") and t.endswith(">"):
                inner = t[len("Array<"):-1]
                members = [m.strip() for m in inner.split(" | ")]
                lines.append(f"  {pname}{opt}: Array<")
                for m in members:
                    lines.append(f"    | {m}")
                lines.append("  >;")
            else:
                members = [m.strip() for m in t.split(" | ")]
                lines.append(f"  {pname}{opt}:")
                for i, m in enumerate(members):
                    suffix = ";" if i == len(members) - 1 else ""
                    lines.append(f"    | {m}{suffix}")
        lines.append("}")
        lines.append("")
    return "\n".join(lines)


PY_KEYWORDS = {
    "False", "None", "True", "and", "as", "assert", "async", "await",
    "break", "class", "continue", "def", "del", "elif", "else", "except",
    "finally", "for", "from", "global", "if", "import", "in", "is",
    "lambda", "nonlocal", "not", "or", "pass", "raise", "return", "try",
    "while", "with", "yield",
}

DART_KEYWORDS = {
    "abstract", "as", "assert", "async", "await", "break", "case", "catch",
    "class", "const", "continue", "default", "do", "else", "enum", "extends",
    "false", "final", "finally", "for", "if", "implements", "import", "in",
    "interface", "is", "new", "null", "override", "rethrow", "return",
    "super", "switch", "this", "throw", "true", "try", "var", "void",
    "while", "with",
}


def py_name(name: str) -> str:
    """Python-safe field name: keywords get a trailing underscore (PEP 8)."""
    candidate = snake(name)
    return candidate + "_" if candidate in PY_KEYWORDS else candidate


def dart_name(name: str) -> str:
    """Dart-safe field name: keywords get a trailing underscore."""
    return name + "_" if name in DART_KEYWORDS else name


def gen_py(schemas: list[tuple[str, str, dict]]) -> str:
    lines = ['"""Code generated by packages/contracts/scripts/generate.py from schemas/. DO NOT EDIT."""', ""]
    lines.append("from __future__ import annotations")
    lines.append("from typing import Any, Literal, NotRequired, TypedDict")
    lines.append("")
    for name, _, doc in schemas:
        class_name = pascal(name)
        lines.append(f"class {class_name}(TypedDict):")
        props = doc.get("properties", {})
        if not props:
            lines.append("    pass")
        for pname, prop in props.items():
            ptype = py_type(prop)
            required = pname in doc.get("required", [])
            field = py_name(pname)
            if required:
                lines.append(f"    {field}: {ptype}")
            else:
                lines.append(f"    {field}: NotRequired[{ptype}]")
        lines.append("")
    # Wire-name aliases: language-safe identifiers map back to canonical names.
    alias_entries = []
    for name, _, doc in schemas:
        class_name = pascal(name)
        pairs = []
        for pname in doc.get("properties", {}):
            safe = py_name(pname)
            if safe != pname:
                pairs.append(f'        "{safe}": "{pname}",')
        if pairs:
            alias_entries.append(f'    "{class_name}": {{\n' + "\n".join(pairs) + "\n    },")
    if alias_entries:
        lines.append("")
        lines.append("WIRE_ALIASES: dict[str, dict[str, str]] = {")
        lines.extend(alias_entries)
        lines.append("}")
        lines.append("")
        lines.append("")
        lines.append("def to_wire(class_name: str, obj: dict[str, Any]) -> dict[str, Any]:")
        lines.append('    """Rename Python-safe identifiers to canonical wire names."""')
        lines.append("    aliases = WIRE_ALIASES.get(class_name, {})")
        lines.append('    return {aliases.get(k, k): v for k, v in obj.items()}')
        lines.append("")
        lines.append("")
        lines.append("def from_wire(class_name: str, obj: dict[str, Any]) -> dict[str, Any]:")
        lines.append('    """Rename canonical wire names back to Python-safe identifiers."""')
        lines.append("    aliases = {v: k for k, v in WIRE_ALIASES.get(class_name, {}).items()}")
        lines.append('    return {aliases.get(k, k): v for k, v in obj.items()}')
        lines.append("")
    return "\n".join(lines)


def gen_dart(schemas: list[tuple[str, str, dict]]) -> str:
    lines = [HEADER]
    lines.append("// Canonical wire names are schema property names (snake_case), verbatim.")
    lines.append("// Keyword-safe Dart identifiers (class_) map back via fromJson/toJson keys.")
    lines.append("")
    lines.append("// ignore_for_file: non_constant_identifier_names")
    lines.append("")
    for name, _, doc in schemas:
        class_name = pascal(name)
        props = doc.get("properties", {})
        lines.append(f"class {class_name} {{")
        # Fields
        for pname, prop in props.items():
            dtype = dart_type(prop)
            field = dart_name(pname)
            optional = pname not in doc.get("required", [])
            nullable = dart_nullable(prop, optional)
            suffix = "?" if nullable else ""
            lines.append(f"  final {dtype}{suffix} {field};")
        # Const static members
        for pname, prop in props.items():
            if is_const(prop):
                field = dart_name(pname)
                lines.append(f"  static const String {field}Const = {json.dumps(const_value(prop))};")
        if props:
            lines.append("")
        # Constructor
        params = []
        for pname, prop in props.items():
            dtype = dart_type(prop)
            field = dart_name(pname)
            optional = pname not in doc.get("required", [])
            nullable = dart_nullable(prop, optional)
            suffix = "?" if nullable else ""
            req = "" if nullable else "required "
            params.append(f"    {req}this.{field},")
        lines.append(f"  const {class_name}({{")
        lines.extend(params)
        lines.append("  });")
        lines.append("")
        # fromJson
        lines.append(f"  factory {class_name}.fromJson(Map<String, dynamic> json) => {class_name}(")
        for pname, prop in props.items():
            dtype = dart_type(prop)
            field = dart_name(pname)
            optional = pname not in doc.get("required", [])
            nullable = dart_nullable(prop, optional)
            if "$ref" in prop:
                sub = dtype
                expr = f"json['{pname}'] == null ? null : {sub}.fromJson(json['{pname}'] as Map<String, dynamic>)"
                if not nullable:
                    expr = f"{sub}.fromJson(json['{pname}'] as Map<String, dynamic>)"
            else:
                if dtype == "double":
                    expr = f"(json['{pname}'] as num).toDouble()" if not nullable else f"json['{pname}'] == null ? null : (json['{pname}'] as num).toDouble()"
                else:
                    cast = _dart_cast(dtype)
                    expr = f"json['{pname}']{f' as {cast}' if cast else ''}"
                    if nullable and cast:
                        expr = f"json['{pname}']{f' as {cast}?' if cast else ''}"
            lines.append(f"    {field}: {expr},")
        lines.append("  );")
        lines.append("")
        # toJson
        lines.append(f"  Map<String, dynamic> toJson() => {{")
        for pname, prop in props.items():
            field = dart_name(pname)
            lines.append(f"    '{pname}': {field},")
        lines.append("  };")
        lines.append("}")
        lines.append("")
    return "\n".join(lines)


def _dart_cast(dtype: str) -> str:
    if dtype in ("String", "bool", "int"):
        return dtype
    if dtype == "double":
        return "num"  # JSON numbers decode as num
    if dtype.startswith("List<") and dtype.endswith(">"):
        inner = dtype[len("List<"):-1]
        if inner.startswith("List<") or inner.startswith("Map<"):
            return f"List<{_dart_cast(inner)}>"
        return f"List<{inner}>"
    if dtype.startswith("Map<"):
        return "Map<String, dynamic>"
    return ""


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="verify committed bindings match schemas")
    args = parser.parse_args()

    schemas = load_schemas()
    rust = gen_rust(schemas)
    ts = gen_ts(schemas)
    py = gen_py(schemas)
    dart = gen_dart(schemas)

    targets = {
        RUST_OUT: rust,
        TS_OUT: ts,
        PY_OUT: py,
        DART_OUT: dart,
    }
    failures = []
    for path, content in targets.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        if args.check:
            if not path.exists():
                failures.append(f"{path} missing")
            elif path.read_text(encoding="utf-8") != content:
                failures.append(f"{path} out of date")
        else:
            path.write_text(content, encoding="utf-8")
    if failures:
        print("contract generation: FAIL - " + "; ".join(failures), file=sys.stderr)
        return 1
    print(f"contract generation: ok ({len(schemas)} schemas, 4 languages)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
