// Code generated by packages/contracts/scripts/generate.py from schemas/. DO NOT EDIT.

use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(deny_unknown_fields)]
pub struct ActionRequest {
    pub action_id: String,
    pub approval_class: String,
    pub arguments: serde_json::Value,
    pub capability_id: String,
    pub expected_state: serde_json::Value,
    pub idempotency_key: String,
    pub invocation: InvocationContext,
    pub principal_id: String,
    pub reversal: String,
    pub risk: String,
    pub tenant_id: String,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(deny_unknown_fields)]
pub struct CapabilityDescriptor {
    pub approval: String,
    pub availability: String,
    pub class: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub data_classes: Option<Vec<String>>,
    pub description: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub event_types: Option<Vec<String>>,
    pub id: String,
    pub idempotency: String,
    pub input_schema: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub locality: Option<String>,
    pub output_schema: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub provider_id: Option<Option<String>>,
    pub required_scopes: Vec<String>,
    pub reversal: String,
    pub risk: String,
    pub version: String,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(deny_unknown_fields)]
pub struct ConnectorManifest {
    pub capabilities: Vec<CapabilityDescriptor>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub certification: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub data_classes: Option<Vec<String>>,
    pub events: Vec<String>,
    pub health: String,
    pub id: String,
    pub license: String,
    pub network_origins: Vec<String>,
    pub runtime: String,
    pub secrets: Vec<String>,
    pub tier: String,
    pub version: String,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(deny_unknown_fields)]
pub struct DeploymentProfile {
    pub backup: serde_json::Value,
    pub components: Vec<String>,
    pub id: String,
    pub mode: String,
    pub nodes: Vec<serde_json::Value>,
    pub release_channel: String,
    pub remote_access: serde_json::Value,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(deny_unknown_fields)]
pub struct EventEnvelope {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub actor_ref: Option<Option<String>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub causation_id: Option<Option<String>>,
    pub correlation_id: String,
    pub data_class: String,
    pub event_id: String,
    pub event_type: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub observed_at: Option<Option<String>>,
    pub occurred_at: String,
    pub payload: serde_json::Value,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub request_id: Option<Option<String>>,
    pub schema_version: String,
    pub source: String,
    pub subject: String,
    pub tenant_id: String,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(deny_unknown_fields)]
pub struct InvocationContext {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub approval_id: Option<Option<String>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub causation_id: Option<Option<String>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub channel: Option<Option<String>>,
    pub correlation_id: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub device_id: Option<Option<String>>,
    pub external_actor_id: String,
    pub external_actor_type: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub objective_id: Option<Option<String>>,
    pub origin_system: String,
    pub request_id: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub room_id: Option<Option<String>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub task_id: Option<Option<String>>,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(deny_unknown_fields)]
pub struct MemoryRecord {
    pub actor: String,
    pub confidence: f64,
    pub content: serde_json::Value,
    pub content_hash: String,
    pub created_at: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub derived_from: Option<Vec<String>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub embedding_ref: Option<Option<String>>,
    pub memory_id: String,
    pub memory_type: String,
    pub namespace: String,
    pub observed_at: String,
    pub purpose: String,
    pub retention: String,
    pub sensitivity: String,
    pub source: String,
    pub status: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub supersedes: Option<Option<String>>,
    pub tenant_id: String,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(deny_unknown_fields)]
pub struct NexusControlObject {
    pub ambiguity: f64,
    pub approval_required: bool,
    pub confidence: f64,
    pub entities: serde_json::Value,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub escalation_reason: Option<Option<String>>,
    pub executable_instruction: bool,
    pub intent: String,
    pub privacy: String,
    pub required_capabilities: Vec<String>,
    pub risk: String,
    pub route: String,
    pub schema_version: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub workflow: Option<Option<serde_json::Value>>,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(deny_unknown_fields)]
pub struct NotificationEnvelope {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub action_ref: Option<Option<String>>,
    pub channels: Vec<String>,
    pub correlation_id: String,
    pub expires_at: String,
    pub notification_id: String,
    pub person_id: String,
    pub privacy: String,
    pub summary: String,
    pub title: String,
    pub urgency: String,
}
