// Code generated by packages/contracts/scripts/generate.py from schemas/. DO NOT EDIT.

export type JsonValue =
  | string
  | number
  | boolean
  | null
  | JsonValue[]
  | { [k: string]: JsonValue };

export interface ActionRequest {
  actionId: string;
  approvalClass: string;
  arguments: Record<string, unknown>;
  capabilityId: string;
  expectedState: Record<string, unknown>;
  idempotencyKey: string;
  invocation: unknown;
  principalId: string;
  reversal: string;
  risk: "R0" | "R1" | "R2" | "R3" | "R4";
  tenantId: string;
}

export interface CapabilityDescriptor {
  approval: "NONE" | "POLICY" | "HUMAN" | "STRONG_HUMAN" | "FOUR_EYES";
  availability: "AVAILABLE" | "DEGRADED" | "UNAVAILABLE" | "UNCERTIFIED";
  class: "QUERY" | "COMMAND" | "WORKFLOW" | "STREAM" | "ADMINISTRATIVE";
  dataClasses?: Array<string> | null;
  description: string;
  eventTypes?: Array<string> | null;
  id: string;
  idempotency: "NOT_APPLICABLE" | "OPTIONAL" | "REQUIRED";
  inputSchema: string;
  locality?:
    | "ANY"
    | "CONTROL_PLANE"
    | "HOME_EDGE"
    | "CLIENT_DEVICE"
    | "HARDWARE_NODE";
  outputSchema: string;
  providerId?: string | null;
  requiredScopes: Array<string>;
  reversal: "NONE" | "COMPENSATING" | "SNAPSHOT" | "IRREVERSIBLE";
  risk: "R0" | "R1" | "R2" | "R3" | "R4";
  version: string;
}

export interface ConnectorManifest {
  capabilities: Array<unknown>;
  certification?: "UNCERTIFIED" | "LAB" | "CERTIFIED" | "DEPRECATED";
  dataClasses?: Array<string> | null;
  events: Array<string>;
  health: string;
  id: string;
  license: string;
  networkOrigins: Array<string>;
  runtime: "RUST" | "PYTHON" | "TYPESCRIPT" | "WASM" | "SIDECAR" | "APPLIANCE";
  secrets: Array<string>;
  tier: "TIER1" | "TIER2" | "TIER3";
  version: string;
}

export interface DeploymentProfile {
  backup: Record<string, unknown>;
  components: Array<string>;
  id: string;
  mode: "MANAGED" | "BYOC" | "EXISTING_SSH" | "HYBRID" | "FULLY_LOCAL";
  nodes: Array<Record<string, unknown>>;
  releaseChannel: "STABLE" | "BETA" | "DEVELOPER" | "PINNED";
  remoteAccess: Record<string, unknown>;
}

export interface EventEnvelope {
  actorRef?: string | null;
  causationId?: string | null;
  correlationId: string;
  dataClass: string;
  eventId: string;
  eventType: string;
  observedAt?: string | null;
  occurredAt: string;
  payload: Record<string, unknown>;
  requestId?: string | null;
  schemaVersion: string;
  source: string;
  subject: string;
  tenantId: string;
}

export interface InvocationContext {
  approvalId?: string | null;
  causationId?: string | null;
  channel?: string | null;
  correlationId: string;
  deviceId?: string | null;
  externalActorId: string;
  externalActorType: "HUMAN" | "SERVICE" | "AGENT" | "DEVICE" | "SYSTEM";
  objectiveId?: string | null;
  originSystem: string;
  requestId: string;
  roomId?: string | null;
  taskId?: string | null;
}

export interface MemoryRecord {
  actor: string;
  confidence: number;
  content: Record<string, unknown>;
  contentHash: string;
  createdAt: string;
  derivedFrom?: Array<string> | null;
  embeddingRef?: string | null;
  memoryId: string;
  memoryType:
    | "WORKING"
    | "EPISODIC"
    | "SEMANTIC"
    | "ENTITY"
    | "PROCEDURAL"
    | "DECISION"
    | "SKILL"
    | "SYSTEM";
  namespace: string;
  observedAt: string;
  purpose: string;
  retention: string;
  sensitivity: string;
  source: string;
  status: "PROPOSED" | "ACTIVE" | "SUPERSEDED" | "REJECTED" | "DELETED";
  supersedes?: string | null;
  tenantId: string;
}

export interface NexusControlObject {
  ambiguity: number;
  approvalRequired: boolean;
  confidence: number;
  entities: Record<string, unknown>;
  escalationReason?: string | null;
  executableInstruction: boolean;
  intent: string;
  privacy:
    | "PUBLIC"
    | "HOUSEHOLD"
    | "PERSONAL"
    | "SENSITIVE"
    | "BUSINESS_CONFIDENTIAL"
    | "SECURITY"
    | "SECRET";
  requiredCapabilities: Array<string>;
  risk: "R0" | "R1" | "R2" | "R3" | "R4";
  route:
    | "DETERMINISTIC"
    | "REFLEX"
    | "CHEAP_API"
    | "FRONTIER_API"
    | "SPECIALIST_AGENT"
    | "CLARIFY"
    | "REJECT";
  schemaVersion: unknown;
  workflow?: Record<string, unknown> | null;
}

export interface NotificationEnvelope {
  actionRef?: string | null;
  channels: Array<
    | "MOBILE_PUSH"
    | "DESKTOP"
    | "SPEAKER"
    | "SMS"
    | "EMAIL"
    | "PHONE"
    | "WATCH"
    | "CAR"
  >;
  correlationId: string;
  expiresAt: string;
  notificationId: string;
  personId: string;
  privacy: string;
  summary: string;
  title: string;
  urgency: "LOW" | "NORMAL" | "HIGH" | "CRITICAL";
}
