// Code generated by packages/contracts/scripts/generate.py from schemas/. DO NOT EDIT.

// Canonical wire names are schema property names (snake_case), verbatim.
// Keyword-safe Dart identifiers (class_) map back via fromJson/toJson keys.

// ignore_for_file: non_constant_identifier_names

class ActionRequest {
  final String action_id;
  final String approval_class;
  final Map<String, dynamic> arguments;
  final String capability_id;
  final Map<String, dynamic> expected_state;
  final String idempotency_key;
  final InvocationContext invocation;
  final String principal_id;
  final String reversal;
  final String risk;
  final String tenant_id;

  const ActionRequest({
    required this.action_id,
    required this.approval_class,
    required this.arguments,
    required this.capability_id,
    required this.expected_state,
    required this.idempotency_key,
    required this.invocation,
    required this.principal_id,
    required this.reversal,
    required this.risk,
    required this.tenant_id,
  });

  factory ActionRequest.fromJson(Map<String, dynamic> json) => ActionRequest(
    action_id: json['action_id'] as String,
    approval_class: json['approval_class'] as String,
    arguments: json['arguments'] as Map<String, dynamic>,
    capability_id: json['capability_id'] as String,
    expected_state: json['expected_state'] as Map<String, dynamic>,
    idempotency_key: json['idempotency_key'] as String,
    invocation: InvocationContext.fromJson(json['invocation'] as Map<String, dynamic>),
    principal_id: json['principal_id'] as String,
    reversal: json['reversal'] as String,
    risk: json['risk'] as String,
    tenant_id: json['tenant_id'] as String,
  );

  Map<String, dynamic> toJson() => {
    'action_id': action_id,
    'approval_class': approval_class,
    'arguments': arguments,
    'capability_id': capability_id,
    'expected_state': expected_state,
    'idempotency_key': idempotency_key,
    'invocation': invocation,
    'principal_id': principal_id,
    'reversal': reversal,
    'risk': risk,
    'tenant_id': tenant_id,
  };
}

class CapabilityDescriptor {
  final String approval;
  final String availability;
  final String class_;
  final List<String>? data_classes;
  final String description;
  final List<String>? event_types;
  final String id;
  final String idempotency;
  final String input_schema;
  final String? locality;
  final String output_schema;
  final String? provider_id;
  final List<String> required_scopes;
  final String reversal;
  final String risk;
  final String version;

  const CapabilityDescriptor({
    required this.approval,
    required this.availability,
    required this.class_,
    this.data_classes,
    required this.description,
    this.event_types,
    required this.id,
    required this.idempotency,
    required this.input_schema,
    this.locality,
    required this.output_schema,
    this.provider_id,
    required this.required_scopes,
    required this.reversal,
    required this.risk,
    required this.version,
  });

  factory CapabilityDescriptor.fromJson(Map<String, dynamic> json) => CapabilityDescriptor(
    approval: json['approval'] as String,
    availability: json['availability'] as String,
    class_: json['class'] as String,
    data_classes: json['data_classes'] as List<String>?,
    description: json['description'] as String,
    event_types: json['event_types'] as List<String>?,
    id: json['id'] as String,
    idempotency: json['idempotency'] as String,
    input_schema: json['input_schema'] as String,
    locality: json['locality'] as String?,
    output_schema: json['output_schema'] as String,
    provider_id: json['provider_id'] as String?,
    required_scopes: json['required_scopes'] as List<String>,
    reversal: json['reversal'] as String,
    risk: json['risk'] as String,
    version: json['version'] as String,
  );

  Map<String, dynamic> toJson() => {
    'approval': approval,
    'availability': availability,
    'class': class_,
    'data_classes': data_classes,
    'description': description,
    'event_types': event_types,
    'id': id,
    'idempotency': idempotency,
    'input_schema': input_schema,
    'locality': locality,
    'output_schema': output_schema,
    'provider_id': provider_id,
    'required_scopes': required_scopes,
    'reversal': reversal,
    'risk': risk,
    'version': version,
  };
}

class ConnectorManifest {
  final List<CapabilityDescriptor> capabilities;
  final String? certification;
  final List<String>? data_classes;
  final List<String> events;
  final String health;
  final String id;
  final String license;
  final List<String> network_origins;
  final String runtime;
  final List<String> secrets;
  final String tier;
  final String version;

  const ConnectorManifest({
    required this.capabilities,
    this.certification,
    this.data_classes,
    required this.events,
    required this.health,
    required this.id,
    required this.license,
    required this.network_origins,
    required this.runtime,
    required this.secrets,
    required this.tier,
    required this.version,
  });

  factory ConnectorManifest.fromJson(Map<String, dynamic> json) => ConnectorManifest(
    capabilities: json['capabilities'] as List<CapabilityDescriptor>,
    certification: json['certification'] as String?,
    data_classes: json['data_classes'] as List<String>?,
    events: json['events'] as List<String>,
    health: json['health'] as String,
    id: json['id'] as String,
    license: json['license'] as String,
    network_origins: json['network_origins'] as List<String>,
    runtime: json['runtime'] as String,
    secrets: json['secrets'] as List<String>,
    tier: json['tier'] as String,
    version: json['version'] as String,
  );

  Map<String, dynamic> toJson() => {
    'capabilities': capabilities,
    'certification': certification,
    'data_classes': data_classes,
    'events': events,
    'health': health,
    'id': id,
    'license': license,
    'network_origins': network_origins,
    'runtime': runtime,
    'secrets': secrets,
    'tier': tier,
    'version': version,
  };
}

class DeploymentProfile {
  final Map<String, dynamic> backup;
  final List<String> components;
  final String id;
  final String mode;
  final List<Map<String, dynamic>> nodes;
  final String release_channel;
  final Map<String, dynamic> remote_access;

  const DeploymentProfile({
    required this.backup,
    required this.components,
    required this.id,
    required this.mode,
    required this.nodes,
    required this.release_channel,
    required this.remote_access,
  });

  factory DeploymentProfile.fromJson(Map<String, dynamic> json) => DeploymentProfile(
    backup: json['backup'] as Map<String, dynamic>,
    components: json['components'] as List<String>,
    id: json['id'] as String,
    mode: json['mode'] as String,
    nodes: json['nodes'] as List<Map<String, dynamic>>,
    release_channel: json['release_channel'] as String,
    remote_access: json['remote_access'] as Map<String, dynamic>,
  );

  Map<String, dynamic> toJson() => {
    'backup': backup,
    'components': components,
    'id': id,
    'mode': mode,
    'nodes': nodes,
    'release_channel': release_channel,
    'remote_access': remote_access,
  };
}

class EventEnvelope {
  final String? actor_ref;
  final String? causation_id;
  final String correlation_id;
  final String data_class;
  final String event_id;
  final String event_type;
  final String? observed_at;
  final String occurred_at;
  final Map<String, dynamic> payload;
  final String? request_id;
  final String schema_version;
  final String source;
  final String subject;
  final String tenant_id;

  const EventEnvelope({
    this.actor_ref,
    this.causation_id,
    required this.correlation_id,
    required this.data_class,
    required this.event_id,
    required this.event_type,
    this.observed_at,
    required this.occurred_at,
    required this.payload,
    this.request_id,
    required this.schema_version,
    required this.source,
    required this.subject,
    required this.tenant_id,
  });

  factory EventEnvelope.fromJson(Map<String, dynamic> json) => EventEnvelope(
    actor_ref: json['actor_ref'] as String?,
    causation_id: json['causation_id'] as String?,
    correlation_id: json['correlation_id'] as String,
    data_class: json['data_class'] as String,
    event_id: json['event_id'] as String,
    event_type: json['event_type'] as String,
    observed_at: json['observed_at'] as String?,
    occurred_at: json['occurred_at'] as String,
    payload: json['payload'] as Map<String, dynamic>,
    request_id: json['request_id'] as String?,
    schema_version: json['schema_version'] as String,
    source: json['source'] as String,
    subject: json['subject'] as String,
    tenant_id: json['tenant_id'] as String,
  );

  Map<String, dynamic> toJson() => {
    'actor_ref': actor_ref,
    'causation_id': causation_id,
    'correlation_id': correlation_id,
    'data_class': data_class,
    'event_id': event_id,
    'event_type': event_type,
    'observed_at': observed_at,
    'occurred_at': occurred_at,
    'payload': payload,
    'request_id': request_id,
    'schema_version': schema_version,
    'source': source,
    'subject': subject,
    'tenant_id': tenant_id,
  };
}

class InvocationContext {
  final String? approval_id;
  final String? causation_id;
  final String? channel;
  final String correlation_id;
  final String? device_id;
  final String external_actor_id;
  final String external_actor_type;
  final String? objective_id;
  final String origin_system;
  final String request_id;
  final String? room_id;
  final String? task_id;

  const InvocationContext({
    this.approval_id,
    this.causation_id,
    this.channel,
    required this.correlation_id,
    this.device_id,
    required this.external_actor_id,
    required this.external_actor_type,
    this.objective_id,
    required this.origin_system,
    required this.request_id,
    this.room_id,
    this.task_id,
  });

  factory InvocationContext.fromJson(Map<String, dynamic> json) => InvocationContext(
    approval_id: json['approval_id'] as String?,
    causation_id: json['causation_id'] as String?,
    channel: json['channel'] as String?,
    correlation_id: json['correlation_id'] as String,
    device_id: json['device_id'] as String?,
    external_actor_id: json['external_actor_id'] as String,
    external_actor_type: json['external_actor_type'] as String,
    objective_id: json['objective_id'] as String?,
    origin_system: json['origin_system'] as String,
    request_id: json['request_id'] as String,
    room_id: json['room_id'] as String?,
    task_id: json['task_id'] as String?,
  );

  Map<String, dynamic> toJson() => {
    'approval_id': approval_id,
    'causation_id': causation_id,
    'channel': channel,
    'correlation_id': correlation_id,
    'device_id': device_id,
    'external_actor_id': external_actor_id,
    'external_actor_type': external_actor_type,
    'objective_id': objective_id,
    'origin_system': origin_system,
    'request_id': request_id,
    'room_id': room_id,
    'task_id': task_id,
  };
}

class MemoryRecord {
  final String actor;
  final double confidence;
  final Map<String, dynamic> content;
  final String content_hash;
  final String created_at;
  final List<String>? derived_from;
  final String? embedding_ref;
  final String memory_id;
  final String memory_type;
  final String namespace;
  final String observed_at;
  final String purpose;
  final String retention;
  final String sensitivity;
  final String source;
  final String status;
  final String? supersedes;
  final String tenant_id;

  const MemoryRecord({
    required this.actor,
    required this.confidence,
    required this.content,
    required this.content_hash,
    required this.created_at,
    this.derived_from,
    this.embedding_ref,
    required this.memory_id,
    required this.memory_type,
    required this.namespace,
    required this.observed_at,
    required this.purpose,
    required this.retention,
    required this.sensitivity,
    required this.source,
    required this.status,
    this.supersedes,
    required this.tenant_id,
  });

  factory MemoryRecord.fromJson(Map<String, dynamic> json) => MemoryRecord(
    actor: json['actor'] as String,
    confidence: (json['confidence'] as num).toDouble(),
    content: json['content'] as Map<String, dynamic>,
    content_hash: json['content_hash'] as String,
    created_at: json['created_at'] as String,
    derived_from: json['derived_from'] as List<String>?,
    embedding_ref: json['embedding_ref'] as String?,
    memory_id: json['memory_id'] as String,
    memory_type: json['memory_type'] as String,
    namespace: json['namespace'] as String,
    observed_at: json['observed_at'] as String,
    purpose: json['purpose'] as String,
    retention: json['retention'] as String,
    sensitivity: json['sensitivity'] as String,
    source: json['source'] as String,
    status: json['status'] as String,
    supersedes: json['supersedes'] as String?,
    tenant_id: json['tenant_id'] as String,
  );

  Map<String, dynamic> toJson() => {
    'actor': actor,
    'confidence': confidence,
    'content': content,
    'content_hash': content_hash,
    'created_at': created_at,
    'derived_from': derived_from,
    'embedding_ref': embedding_ref,
    'memory_id': memory_id,
    'memory_type': memory_type,
    'namespace': namespace,
    'observed_at': observed_at,
    'purpose': purpose,
    'retention': retention,
    'sensitivity': sensitivity,
    'source': source,
    'status': status,
    'supersedes': supersedes,
    'tenant_id': tenant_id,
  };
}

class NexusControlObject {
  final double ambiguity;
  final bool approval_required;
  final double confidence;
  final Map<String, dynamic> entities;
  final String? escalation_reason;
  final bool executable_instruction;
  final String intent;
  final String privacy;
  final List<String> required_capabilities;
  final String risk;
  final String route;
  final String schema_version;
  final Map<String, dynamic>? workflow;
  static const String schema_versionConst = "1.0.0";

  const NexusControlObject({
    required this.ambiguity,
    required this.approval_required,
    required this.confidence,
    required this.entities,
    this.escalation_reason,
    required this.executable_instruction,
    required this.intent,
    required this.privacy,
    required this.required_capabilities,
    required this.risk,
    required this.route,
    required this.schema_version,
    this.workflow,
  });

  factory NexusControlObject.fromJson(Map<String, dynamic> json) => NexusControlObject(
    ambiguity: (json['ambiguity'] as num).toDouble(),
    approval_required: json['approval_required'] as bool,
    confidence: (json['confidence'] as num).toDouble(),
    entities: json['entities'] as Map<String, dynamic>,
    escalation_reason: json['escalation_reason'] as String?,
    executable_instruction: json['executable_instruction'] as bool,
    intent: json['intent'] as String,
    privacy: json['privacy'] as String,
    required_capabilities: json['required_capabilities'] as List<String>,
    risk: json['risk'] as String,
    route: json['route'] as String,
    schema_version: json['schema_version'] as String,
    workflow: json['workflow'] as Map<String, dynamic>?,
  );

  Map<String, dynamic> toJson() => {
    'ambiguity': ambiguity,
    'approval_required': approval_required,
    'confidence': confidence,
    'entities': entities,
    'escalation_reason': escalation_reason,
    'executable_instruction': executable_instruction,
    'intent': intent,
    'privacy': privacy,
    'required_capabilities': required_capabilities,
    'risk': risk,
    'route': route,
    'schema_version': schema_version,
    'workflow': workflow,
  };
}

class NotificationEnvelope {
  final String? action_ref;
  final List<String> channels;
  final String correlation_id;
  final String expires_at;
  final String notification_id;
  final String person_id;
  final String privacy;
  final String summary;
  final String title;
  final String urgency;

  const NotificationEnvelope({
    this.action_ref,
    required this.channels,
    required this.correlation_id,
    required this.expires_at,
    required this.notification_id,
    required this.person_id,
    required this.privacy,
    required this.summary,
    required this.title,
    required this.urgency,
  });

  factory NotificationEnvelope.fromJson(Map<String, dynamic> json) => NotificationEnvelope(
    action_ref: json['action_ref'] as String?,
    channels: json['channels'] as List<String>,
    correlation_id: json['correlation_id'] as String,
    expires_at: json['expires_at'] as String,
    notification_id: json['notification_id'] as String,
    person_id: json['person_id'] as String,
    privacy: json['privacy'] as String,
    summary: json['summary'] as String,
    title: json['title'] as String,
    urgency: json['urgency'] as String,
  );

  Map<String, dynamic> toJson() => {
    'action_ref': action_ref,
    'channels': channels,
    'correlation_id': correlation_id,
    'expires_at': expires_at,
    'notification_id': notification_id,
    'person_id': person_id,
    'privacy': privacy,
    'summary': summary,
    'title': title,
    'urgency': urgency,
  };
}
