// Code generated by packages/contracts/scripts/generate.py from schemas/. DO NOT EDIT.

export type JsonValue =
  | string
  | number
  | boolean
  | null
  | JsonValue[]
  | { [k: string]: JsonValue };

export interface ActionRequest {
  action_id: string;
  approval_class: string;
  arguments: Record<string, unknown>;
  capability_id: string;
  expected_state: Record<string, unknown>;
  idempotency_key: string;
  invocation: InvocationContext;
  principal_id: string;
  reversal: string;
  risk: "R0" | "R1" | "R2" | "R3" | "R4";
  tenant_id: string;
}

export interface CapabilityDescriptor {
  approval: "NONE" | "POLICY" | "HUMAN" | "STRONG_HUMAN" | "FOUR_EYES";
  availability: "AVAILABLE" | "DEGRADED" | "UNAVAILABLE" | "UNCERTIFIED";
  class: "QUERY" | "COMMAND" | "WORKFLOW" | "STREAM" | "ADMINISTRATIVE";
  data_classes?: Array<string> | null;
  description: string;
  event_types?: Array<string> | null;
  id: string;
  idempotency: "NOT_APPLICABLE" | "OPTIONAL" | "REQUIRED";
  input_schema: string;
  locality?:
    | "ANY"
    | "CONTROL_PLANE"
    | "HOME_EDGE"
    | "CLIENT_DEVICE"
    | "HARDWARE_NODE";
  output_schema: string;
  provider_id?: string | null;
  required_scopes: Array<string>;
  reversal: "NONE" | "COMPENSATING" | "SNAPSHOT" | "IRREVERSIBLE";
  risk: "R0" | "R1" | "R2" | "R3" | "R4";
  version: string;
}

export interface ConnectorManifest {
  capabilities: Array<CapabilityDescriptor>;
  certification?: "UNCERTIFIED" | "LAB" | "CERTIFIED" | "DEPRECATED";
  data_classes?: Array<string> | null;
  events: Array<string>;
  health: string;
  id: string;
  license: string;
  network_origins: Array<string>;
  runtime: "RUST" | "PYTHON" | "TYPESCRIPT" | "WASM" | "SIDECAR" | "APPLIANCE";
  secrets: Array<string>;
  tier: "TIER1" | "TIER2" | "TIER3";
  version: string;
}

export interface DeploymentProfile {
  backup: Record<string, unknown>;
  components: Array<string>;
  id: string;
  mode: "MANAGED" | "BYOC" | "EXISTING_SSH" | "HYBRID" | "FULLY_LOCAL";
  nodes: Array<Record<string, unknown>>;
  release_channel: "STABLE" | "BETA" | "DEVELOPER" | "PINNED";
  remote_access: Record<string, unknown>;
}

export interface EventEnvelope {
  actor_ref?: string | null;
  causation_id?: string | null;
  correlation_id: string;
  data_class: string;
  event_id: string;
  event_type: string;
  observed_at?: string | null;
  occurred_at: string;
  payload: Record<string, unknown>;
  request_id?: string | null;
  schema_version: string;
  source: string;
  subject: string;
  tenant_id: string;
}

export interface InvocationContext {
  approval_id?: string | null;
  causation_id?: string | null;
  channel?: string | null;
  correlation_id: string;
  device_id?: string | null;
  external_actor_id: string;
  external_actor_type: "HUMAN" | "SERVICE" | "AGENT" | "DEVICE" | "SYSTEM";
  objective_id?: string | null;
  origin_system: string;
  request_id: string;
  room_id?: string | null;
  task_id?: string | null;
}

export interface MemoryRecord {
  actor: string;
  confidence: number;
  content: Record<string, unknown>;
  content_hash: string;
  created_at: string;
  derived_from?: Array<string> | null;
  embedding_ref?: string | null;
  memory_id: string;
  memory_type:
    | "WORKING"
    | "EPISODIC"
    | "SEMANTIC"
    | "ENTITY"
    | "PROCEDURAL"
    | "DECISION"
    | "SKILL"
    | "SYSTEM";
  namespace: string;
  observed_at: string;
  purpose: string;
  retention: string;
  sensitivity:
    | "PUBLIC"
    | "HOUSEHOLD"
    | "PERSONAL"
    | "SENSITIVE"
    | "BUSINESS_CONFIDENTIAL"
    | "SECURITY"
    | "SECRET";
  source: string;
  status: "PROPOSED" | "ACTIVE" | "SUPERSEDED" | "REJECTED" | "DELETED";
  supersedes?: string | null;
  tenant_id: string;
}

export interface NexusControlObject {
  ambiguity: number;
  approval_required: boolean;
  confidence: number;
  entities: Record<string, unknown>;
  escalation_reason?: string | null;
  executable_instruction: boolean;
  intent: string;
  privacy:
    | "PUBLIC"
    | "HOUSEHOLD"
    | "PERSONAL"
    | "SENSITIVE"
    | "BUSINESS_CONFIDENTIAL"
    | "SECURITY"
    | "SECRET";
  required_capabilities: Array<string>;
  risk: "R0" | "R1" | "R2" | "R3" | "R4";
  route:
    | "DETERMINISTIC"
    | "REFLEX"
    | "CHEAP_API"
    | "FRONTIER_API"
    | "SPECIALIST_AGENT"
    | "CLARIFY"
    | "REJECT";
  schema_version: "1.0.0";
  workflow?: Record<string, unknown> | null;
}

export interface NotificationEnvelope {
  action_ref?: string | null;
  channels: Array<
    | "MOBILE_PUSH"
    | "DESKTOP"
    | "SPEAKER"
    | "SMS"
    | "EMAIL"
    | "PHONE"
    | "WATCH"
    | "CAR"
  >;
  correlation_id: string;
  expires_at: string;
  notification_id: string;
  person_id: string;
  privacy: string;
  summary: string;
  title: string;
  urgency: "LOW" | "NORMAL" | "HIGH" | "CRITICAL";
}
